services:
  # Uncomment the following to deploy this app as a static site on render
  - type: web
    name: nextjs-static
    runtime: static
    buildCommand: npm run build
    staticPublishPath: out
    pullRequestPreviewsEnabled: true # optional
    envVars:
      - key: NODE_ENV
        value: production
