services:
  - type: web
    name: bispo.eti.br
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./out
    pullRequestPreviewsEnabled: true
    envVars:
      - key: NODE_ENV
        value: production
